brew "git"
brew "gh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "alt-tab"
cask "chatgpt"
cask "claude-code"
cask "codex"
cask "font-jetbrains-mono"
cask "ghostty"
cask "raycast"
cask "tailscale-app"
cask "thebrowsercompany-dia"
cask "zed"
